name: Android UI Tests with Firebase Test Lab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Up Build Job
        run: echo Setting Up Build Job
        
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build App APK
        run: ./gradlew assembleDebug
        
      - name: Build UI Test APK
        run: ./gradlew assembleAndroidTest
        
      - name: Upload APKs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: "**/app/build/outputs/apk/**/*.apk"

  uiTests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          name: app-apks
          path: ./apks

      - name: Run UI Tests on Firebase Test Lab
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_KEY }}
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GOOGLE_CLOUD_KEY }}
          gcloud --quiet config set project ${{ secrets.TESTLAB_PROJECT_ID }}
          gcloud firebase test android run \
            --type instrumentation \
            --app ./apks/app-debug.apk \
            --test ./apks/app-debug-androidTest.apk \
            --device model=Pixel3,version=30,locale=en,orientation=portrait

      - name: Upload Firebase Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firebase-test-results
          path: "testlab-results/"
