name: Android UI Tests with Gradle Managed Devices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_GMD:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Accept Android SDK Licenses
        run: |
          yes | sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Required Android System Image
        run: |
          yes | sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;aosp_atd;x86"

      - name: Fix SDK Permissions
        run: sudo chmod -R 777 $ANDROID_SDK_ROOT

      - name: Clean Gradle Cache
        working-directory: ui/espresso/BasicSample
        run: ./gradlew clean

      - name: Create AVD Manually
        run: |
          echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test_avd -k "system-images;android-30;aosp_atd;x86" --device "Nexus 5"

      - name: Grant execute permission for gradlew
        working-directory: ui/espresso/BasicSample
        run: chmod +x gradlew

      - name: Run UI Tests
        working-directory: ui/espresso/BasicSample
        run: ./gradlew connectedAndroidTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: testResults
          path: app/build/reports/androidTests/managedDevice/allDevices/index.html
